### ISSUE TITLE
CI has no Windows job on PRs — a Windows-breaking change reached main undetected

### ISSUE THREAD

**Issue by RezaRassool** [Kwaai-AI-Lab/KwaaiNet#146]
`main` did not compile on Windows between #130 and #142. Nothing in review or CI could have caught it.

## What happened

#130 added `net` to `GrpcServerHandle` and populated it only in the `#[cfg(unix)]` constructor arm. The field is declared ungated, so Windows failed:

```
error[E0063]: missing field `net` in initializer of `GrpcServerHandle`
    --> crates\kwaai-cli\src\grpc_server.rs:1971:9
```

It surfaced only when metro-win tried to build `main` for a regression pass — days after the merge — and was fixed in #142.

## Why nothing caught it

Review did not: I merged current `main` into #130, built and tested it, and reported it green. On macOS.

CI did not, and could not. Every workflow is Linux:

```
.github/workflows/ci.yml                 runs-on: ubuntu-latest
.github/workflows/ci-kwaai-platform.yml  runs-on: ubuntu-latest
.github/workflows/ci-kwaai-network.yml   runs-on: ubuntu-latest
…all six domain workflows
```

Windows is built **only** in the release pipeline (`build-cuda-artifacts`, `windows-latest`). So the first Windows compile of any change happens when a release is cut — or when a human happens to build there.

That is the gap: a Windows-breaking change passes review, passes CI, lands on `main`, and waits.

## Suggested fix

A `cargo check --target x86_64-pc-windows-msvc` job on PRs touching `core/`.

**Check, not build.** Type checking catches the whole `E0063` class — cfg-gated fields, platform-specific imports, missing `#[cfg]` arms — without needing CUDA or the full MSVC/link toolchain on the runner. It is fast and it would have caught this in about a minute.

Not viable as a local pre-check: I tried `cargo check --target x86_64-pc-windows-msvc` from macOS to verify #142 and it dies in `ring`'s build script, which wants a Windows C toolchain. On a `windows-latest` runner it is trivial.

## Scope worth deciding

- Which paths trigger it — `core/**` is the obvious filter, matching the existing domain workflows.
- Whether to also check `x86_64-unknown-linux-musl`, which ships in releases and has the same "only built at release time" exposure.
- Whether a failure blocks merge or only warns. Blocking is right in my view: the cost of a broken `main` fell on a machine that could not then do the work it was set up for.

## Related

- #130 introduced it, #142 fixed it.
- The same shape as #145, filed alongside this: a real failure that no signal surfaced until a human went looking.
